FROM nginx

ARG HXE_HOST
ARG HXE_PORT
ENV HXE_HOST=${HXE_HOST} \
  HXE_PORT=${HXE_PORT}

COPY ./nginx/host.* /etc/nginx/

CMD /bin/sh -c \ 
  "envsubst '\${HXE_HOST} \${HXE_PORT}' < /etc/nginx/host.tmpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"